{% set name = "xseof" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: bd9d1a5b55cbba9b1c712fb78f4d657b40087afbbc2e1f0c610e943989f668d5

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - xsdata
    - lxml

test:
  imports:
    - xseof
  commands:
      - pip check
      - python -m pytest
  requires:
    - pytest
  source_files:
    - tests

about:
  home: https://github.com/avalentino/xseof
  license: Apache-2.0
  license_file: LICENSE.txt
  summary: 'I/O library for the ESA EOF files based on xsdata'
  description: |
    This package provides a set of "dataclasses", comapible with the
    xsdata Python library, to access and make I/O operation on the XML
    files in the ESA Earth Observation Ground Segment File Format (EOF).

    In particular, this package supports all the XML based orbit and
    attitude products.
  dev_url: https://github.com/avalentino/xseof

extra:
  recipe-maintainers:
    - avalentino
