{% set name = "geomodels" %}
{% set version = "1.0.0b4" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 9f15635b3c58d33584843f004aa48cdd813f8eb25b2f6e69c17b735140fbeb3c

build:
  number: 0
  entry_points:
    - geomodels-cli = geomodels.__main__:main
  script:
    - make embed
    - {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('cxx') }}
    - make
  host:
    - python
    - cython
    - setuptools
  run:
    - numpy
    - python
    - dataclasses  # [py<37]
    - tqdm
    - argcomplete

test:
  requires:
    - pytest
  imports:
    - geomodels
    - geomodels.tests
  commands:
    - geomodels-cli --help
    - geomodels-cli install-data -d data recommended
    - python -m geomodels info
    - env GEOGRAPHICLIB_DATA=./data python -m pytest --pyargs geomodels

about:
  home: "https://github.com/avalentino/geomodels"
  license: MIT
  license_family: MIT
  license_file:
  summary: "Python package for Earth data models management"
  doc_url:
  dev_url:

extra:
  recipe-maintainers:
    - avalentino

# conda build --output-folder output --python 3.8 geomodels
