package:
  name: pyepr
  version: 0.9.2

source:
  fn: pyepr-0.9.2.tar.gz
  url: https://pypi.python.org/packages/source/p/pyepr/pyepr-0.9.2.tar.gz
  md5: 18d5e73acaa1cef408de0b1614b7a186

requirements:
  build:
    - python
    - numpy
    - cython
  run:
    - python
    - numpy

#build:
#  number: 0

test:
  imports:
    - epr

about:
  home: http://avalentino.github.com/pyepr
  license: GPL3
  summary: Python ENVISAT Product Reader API

