# Note: there are many handy hints in comments in this example -- remove them when you've finalized your recipe

# Jinja variables help maintain the recipe as you'll update the version only here.
{% set name = "pyepr" %}
{% set version = "0.9.5" %}
{% set sha256 = "87591cdfcb5c5534abf5a51b5f8d50ef7654eb83c81aaa57ca8999803613d64a" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - setuptools
    - pip
    - numpy >=1.5
    - cython
  run:
    - python
    - numpy >=1.5

test:
  source_files:
    - tests/test_all.py
  imports:
    - epr

about:
  home: http://avalentino.github.com/pyepr
  license: GPL-3.0
  license_family: LGPL
  license_file: LICENSE.txt
  summary: 'Python ENVISAT Product Reader API'

  # The remaining entries in this section are optional, but recommended
  description: |
    PyEPR provides Python bindings for the ENVISAT Product Reader C API
    (EPR API) for reading satellite data from ENVISAT ESA (European Space
    Agency) mission.
    PyEPR, as well as the EPR API for C, supports ENVISAT MERIS, AATSR
    Level 1B and Level 2 and also ASAR data products. It provides access to
    the data either on a geophysical (decoded, ready-to-use pixel samples)
    or on a raw data layer. The raw data access makes it possible to read
    any data field contained in a product file.
  doc_url: http://avalentino.github.io/pyepr/html/index.html
  dev_url: https://github.com/avalentino/pyepr

extra:
  recipe-maintainers:
    - avalentino

# conda build --output-folder output --python 3.6 pyepr
