package:
  name: pyepr
  version: 0.8.2

source:
  fn: pyepr-0.8.2.tar.gz
  url: https://pypi.python.org/packages/source/p/pyepr/pyepr-0.8.2.tar.gz
  md5: afb7a0c8351c1b903a59cff3883c82db

requirements:
  build:
    - python
    - numpy
    - cython
  run:
    - python
    - numpy

#build:
#  number: 0

test:
  imports:
    - epr

about:
  home: http://avalentino.github.com/pyepr
  license: GPL3
  summary: Python ENVISAT Product Reader API
