package:
  name: pyepr
  version: 0.9.3

source:
  fn: pyepr-0.9.3.tar.gz
  url: https://pypi.python.org/packages/source/p/pyepr/pyepr-0.9.3.tar.gz
  md5: de274a94f8a2c44227e85a515af32291

requirements:
  build:
    - python
    - numpy
    - cython
  run:
    - python
    - numpy

#build:
#  number: 0

test:
  imports:
    - epr

about:
  home: http://avalentino.github.com/pyepr
  license: GPL3
  summary: Python ENVISAT Product Reader API

