package:
  name: hashsum
  version: "1.2.1"

source:
  fn: hashsum-1.2.1.tar.gz
  url: https://pypi.org/packages/source/h/hashsum/hashsum-1.2.1.tar.gz
  md5: 3e0b31b403273c43544bc507bfd8b29c
#  patches:
   # List any patch files here
   # - fix.patch

build:
  # noarch_python: True
  # preserve_egg_dir: True
  entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - hashsum = hashsum:main
    #
    # Would create an entry point called hashsum that calls hashsum.main()

    - hashsum=hashsum:main

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - enum34 # [not (py34 or py35)]

  run:
    - python
    - enum34 # [not (py34 or py35)]

test:
  # Python imports
  # imports:

  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

    - hashsum --help

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/avalentino/hashsum
  license: BSD License
  summary: 'Python drop-in replacement for md5sum and co.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
