{% set version = "1.4.1" %}

package:
  name: hashsum
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/h/hashsum/hashsum-{{ version }}.tar.gz
  sha256: 2c40505ab82578651f9875241c48d03a1149c36eabd858907b7f3ab047a8c5e7

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - setuptools
    - pip
  run:
    - python
    - argcomplete

test:
  requires:
    - pytest
  source_files:
    - tests
  imports:
    - hashsum
  commands:
    - hashsum --help
    - python -m pytest -v -p no:warnings -p no:logging

about:
  home: https://github.com/avalentino/hashsum
  license: BSD
  license_file: LICENSE.txt
  summary: 'Python drop-in replacement for md5sum and co.'
  description: |
    The hashsum package provides a command line tool for hash-sum
    computation and check. It can use different algorithms and it
    is compatible with related GNU utilities.
  doc_url: https://github.com/avalentino/hashsum
  dev_url: https://github.com/avalentino/hashsum
  doc_source_url: https://github.com/avalentino/hashsum/blob/master/README.rst

extra:
  recipe-maintainers:
    - avalentino
