# Note: there are many handy hints in comments in this example -- remove them when you've finalized your recipe

# Jinja variables help maintain the recipe as you'll update the version only here.
{% set name = "hashsum" %}
{% set version = "1.2.1" %}
{% set sha256 = "cd0259e316c71b078a46129a2c1ba508e341653bd664a7e37dc20688ccc4d1a7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - enum34 # [not (py34 or py35)]
  run:
    - python
    - enum34 # [not (py34 or py35)]

test:
  source_files:
    - tests
  imports:
    - hashsum

  commands:
    - hashsum --help

about:
  home: https://github.com/avalentino/hashsum
  license: BSD
  license_file: LICENSE.txt
  summary: 'Python drop-in replacement for md5sum and co.'
  description: |
    The hashsum package provides a command line tool for hash-sum
    computation and check. It can use different algorithms and it
    is compatible with related GNU utilities.
  doc_url: https://github.com/avalentino/hashsum
  dev_url: https://github.com/avalentino/hashsum

extra:
  recipe-maintainers:
    - avalentino
